# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaugu <marvin@42lausanne.ch>               +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/24 12:03:36 by aaugu             #+#    #+#              #
#    Updated: 2022/10/25 16:19:26 by aaugu            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# SRCS	= main.c ft.c ft_compare.c ft_parsing.c parsing_dict.c triplet_slicer.c
# OBJS	= ${SRCS:.c=.o}
# NAME	= rush-02
# CC		= cc
# CFLAGS	= -Wall -Wextra -Werror
# RM		= rm -f

# .c.o:
# 			${CC} ${CFLAGS} -c $< -o ${<:.c=.o}

# ${NAME}:	${OBJS}
# 			${CC} -o ${NAME} ${OBJS}

# clean:
# 			${RM} ${OBJS}

# fclean:		clean
# 			${RM} ${NAME}

# .PHONY:		clean fclean